repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: frontend/build/
    -   id: end-of-file-fixer
        exclude: frontend/build/
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: forbid-new-submodules
    -   id: check-symlinks

# Python code quality
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        exclude: '^migrations/'
        args: ['--profile', 'black']

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: '^migrations/|test_*'
        args: ['--max-line-length=120']
        additional_dependencies:
        -   flake8-docstrings
        -   flake8-import-order
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-bandit
        -   flake8-builtins
        -   flake8-django
        -   flake8-eradicate
        -   flake8-logging-format
        -   flake8-annotations
        -   flake8-pytest-style

-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        exclude: '^migrations/'
        args: ['--line-length=120']

# Security scanning
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
        args:
        - -s
        - B101,B104,B603,B607
        exclude: '^tests/'

# Type checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        exclude: '^migrations/|tests/'
        additional_dependencies:
        -   types-requests
        -   django-stubs
        -   djangorestframework-stubs

# Comprehensive secrets detection
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
        args: ['--config-path', '.gitleaks.toml', '--verbose']
        exclude: '^tests/test_data/'

# Docker security scanning
-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    -   id: hadolint
        args: ['--ignore', 'DL3008', '--ignore', 'DL3013']

# JavaScript/React hooks
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.1.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        args: ['--fix']
        additional_dependencies:
        -   eslint@8.57.0
        -   eslint-plugin-react@7.33.2
        -   eslint-config-prettier@9.1.0
        -   eslint-plugin-import@2.29.1
        -   eslint-plugin-jsx-a11y@6.8.0
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-plugin-security@2.1.0
        -   '@typescript-eslint/eslint-plugin@7.1.0'
        -   '@typescript-eslint/parser@7.1.0'

# Run tests on commit
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-critical
        description: Run critical pytest tests
        entry: python -m pytest -xvs chess_mate/core/tests/critical/
        language: system
        pass_filenames: false
        always_run: true

# Check for Django security issues
-   repo: local
    hooks:
    -   id: django-check
        name: django-check
        entry: python chess_mate/manage.py check --deploy
        language: system
        pass_filenames: false
        always_run: true

# Documentation validation
-   repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
    -   id: doc8
        args: ['--max-line-length=120']

# Final catch-all checks
-   repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.1
    hooks:
    -   id: validate_manifest
