global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'chessmate'
    scheme: http
    static_configs:
      - targets: ['web:8000']
        labels:
          environment: 'production'
          instance: 'ec2-3-133-97-72.us-east-2.compute.amazonaws.com'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'production'
          instance: 'ec2-3-133-97-72.us-east-2.compute.amazonaws.com'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          environment: 'production'
          instance: 'ec2-3-133-97-72.us-east-2.compute.amazonaws.com'
