# Generated by Django 4.2.20 on 2025-04-04 19:20

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import django.utils.timezone


def repair_profile_columns(apps, schema_editor):
    """Safely repair missing columns in core_profile table."""
    with connection.cursor() as cursor:
        # Check and handle each column individually
        try:
            # Check if chesscom_username exists and handle it
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='core_profile' AND column_name='chesscom_username'
                )
            """)
            if cursor.fetchone()[0]:
                cursor.execute("ALTER TABLE core_profile DROP COLUMN IF EXISTS chesscom_username;")
        except Exception as e:
            print(f"Warning: Could not drop chesscom_username: {e}")
        
        try:
            # Ensure chess_com_username exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='core_profile' AND column_name='chess_com_username'
                )
            """)
            if not cursor.fetchone()[0]:
                cursor.execute("ALTER TABLE core_profile ADD COLUMN chess_com_username varchar(50) NULL DEFAULT '';")
        except Exception as e:
            print(f"Warning: Could not add chess_com_username: {e}")
        
        try:
            # Check and fix lichess_username if needed
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name='core_profile' AND column_name='lichess_username'
                )
            """)
            if cursor.fetchone()[0]:
                cursor.execute("""
                    SELECT data_type, character_maximum_length 
                    FROM information_schema.columns 
                    WHERE table_name='core_profile' AND column_name='lichess_username'
                """)
                result = cursor.fetchone()
                if result and (result[1] is None or result[1] < 50):
                    cursor.execute("ALTER TABLE core_profile ALTER COLUMN lichess_username TYPE varchar(50);")
        except Exception as e:
            print(f"Warning: Could not fix lichess_username: {e}")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('credits_per_period', models.IntegerField(default=0)),
                ('period_length', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_tiers',
                'ordering': ['price'],
            },
        ),
        # Repair schema to handle missing/incorrect columns
        migrations.RunPython(repair_profile_columns),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credits_per_period', models.IntegerField(default=0)),
                ('credits_remaining', models.IntegerField(default=0)),
                ('last_credit_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptiontier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
