# Generated by Django 5.0.11 on 2025-02-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
