# Generated by Django 5.0.11 on 2025-02-08 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_black_elo_game_time_control_game_white_elo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='core_profil_user_id_802922_idx',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rating',
            new_name='blitz_rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='bullet_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='profile',
            name='classical_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='profile',
            name='rapid_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='core_profil_user_id_155486_idx'),
        ),
    ]
