# Generated by Django 4.2.20 on 2025-04-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_credit_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
