# Generated by Django 5.0.11 on 2025-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_core_profil_user_id_802922_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chesscom_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lichess_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
