# Generated by Django 5.0.11 on 2025-02-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_chesscom_username_profile_lichess_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_history',
            field=models.JSONField(default=dict),
        ),
    ]
