# Generated by Django 4.2.20 on 2025-04-07 19:16

from django.db import migrations, models, connection
import django.db.models.deletion
def safe_rename_index(apps, schema_editor):
    """Safely rename index if it exists."""
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = 'game_analys_created_b2b4a9_idx'")
            if cursor.fetchone():
                cursor.execute("ALTER INDEX game_analys_created_b2b4a9_idx RENAME TO core_gamean_created_23259a_idx;")
        except Exception:
            pass


def safe_remove_index(apps, schema_editor):
    """Safely remove index if it exists."""
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = 'game_analys_cache_k_738172_idx'")
            if cursor.fetchone():
                cursor.execute("DROP INDEX IF EXISTS game_analys_cache_k_738172_idx;")
        except Exception:
            pass




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_game_game_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameanalysis',
            options={'verbose_name': 'Game Analysis', 'verbose_name_plural': 'Game Analyses'},
        ),
        migrations.RunPython(safe_remove_index),
        migrations.RunPython(safe_rename_index),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='analysis_metadata',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='cache_key',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='phase_metrics',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='positional_metrics',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='study_plan',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='tactical_metrics',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='time_control_feedback',
        ),
        migrations.RemoveField(
            model_name='gameanalysis',
            name='time_metrics',
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='accuracy_black',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='accuracy_white',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gameanalysis',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameanalysis',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gameanalysis', to='core.game'),
        ),
        migrations.AddIndex(
            model_name='gameanalysis',
            index=models.Index(fields=['game'], name='core_gamean_game_id_dc376d_idx'),
        ),
        migrations.AlterModelTable(
            name='gameanalysis',
            table=None,
        ),
    ]
